### ISSUE TITLE
Tech tree: Unlock stock parts when a BDB equivalent is available

### ISSUE THREAD

**Issue by bfrobin446** [bfrobin446/KSP-RP64#1]
# Command pods

- [x] Mk 1 pod to Engineering 101
- [x] Making History Vostok to Engineering 101

# Science experiments

The BDB philosophy is that for the first couple of tiers, most of your science comes from single-part satellites with experiments built in. Standalone experiment parts are introduced with the Ranger probes at tier 3.

- [x] Thermometer to Survivability (with Ranger Block 1 experiments)
- [x] Mystery Goo to Engineering 101 (with Mercury nose that includes the same experiment)
- [ ] ~Should the BDB Geiger counter come down to tier 3 (Survivability) since Explorer 1 has the same experiment at tier 1?~
      - Geiger counters on early probes have a multiplier set so they don't return all of the science for the experiment type. If we want every experiment that's available on an early probe to show up as a discrete experiment at tier 3, we'll need to introduce "early" versions that return partial results.

# Engines

# Other parts
- [ ] 0.625m parachute to Engineering 101
- [x] TT-18 launch clamp to start (if Modular Launch Clamps isn't installed; else make sure a Vanguard launch stand from the mod is available in start)
- [ ] EVA parachute to Survivability
- [ ] EVA jetpack to Flight Control (where a lot of RCS blocks unlock)
